-- =====================================================================
-- NAP-IQ Sample / Dummy Data
-- For local development and testing only. No real customer information
-- is used here — all names, addresses, and numbers are fictional.
--
-- Regenerated: one NAP per barangay for all 26 barangays of Sta. Cruz,
-- Laguna (Alipit, Bagumbayan, Bubukal, Calios, Duhat, Gatid, Jasaan,
-- Labuin, Malinao, Oogong, Pagsawitan, Palasan, Patimbao, Poblacion I-V,
-- San Jose, San Juan, San Pablo Norte/Sur, Santisima Cruz, Santo Angel
-- Central/Norte/Sur). Each NAP has 1-3 randomly generated connected
-- subscribers and 1-2 randomly generated reported technical issues, each
-- issue pinned at its subscriber's *exact* coordinates (required by the
-- Report Issue "pin must match the subscriber's exact location" rule).
-- Generated by database/gen_seed.py with random.seed(42) for reproducibility.
--
-- Usage (MySQL command line, after schema.sql has been run):
--   mysql -u root -p nap_iq < database/seed.sql
-- =====================================================================

USE nap_iq;

-- Note: password_hash values below are real Werkzeug pbkdf2:sha256
-- hashes (Phase 7), generated for these DEMO passwords only —
-- change them (or delete these seed rows) before any real deployment:
--   admin1      / Admin@12345
--   tech1       / Tech@12345
--   tech2       / Tech@12345
--   collector1  / Collect@12345
--   customer1   / User@12345

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
INSERT INTO users (username, password_hash, full_name, role, email, phone_number, status) VALUES
('admin1',    'pbkdf2:sha256:1000000$3Rr8CEHSh8bQmUSv$c6903bfc58bc0a263dd6df5e8b5a1a6ad1b9b1fb15e80541c977a1cfac0afe83', 'Juana Dela Cruz',   'administrator',      'juana.delacruz@example.com', '09170000001', 'active'),
('tech1',     'pbkdf2:sha256:1000000$1juq9BKWzYkyYKCS$d3d239b61c93707ea9cab4e53c5a415152007688f867ac54a08d993cf028d2b6', 'Marco Reyes',       'field_assistant',         'marco.reyes@example.com',    '09170000002', 'active'),
('tech2',     'pbkdf2:sha256:1000000$1gNzA7t1BDj164SQ$64d656ca2b533fdc0fa37619339c03147e9ee757f1c5a10e05d221fe3d4c196e', 'Liza Fernandez',    'field_assistant',         'liza.fernandez@example.com', '09170000003', 'active'),
('collector1','pbkdf2:sha256:1000000$tOJDSeW1HAQ0NrUi$87fbdf4768721993e54ec39bdda17c8e4c352724a9d7dbb0eadbec36e8f874cc', 'Paolo Santos',      'payment_collector',  'paolo.santos@example.com',   '09170000004', 'active'),
('customer1', 'pbkdf2:sha256:1000000$OxBMrI4FkyzFasJp$a36bad799898939ff80efb51036fa5cc0354183328aa2bcac90bb6ea357358b9', 'Ana Villanueva',    'user',               'ana.villanueva@example.com', '09171111111', 'active');

-- ---------------------------------------------------------------------
-- naps -- one per barangay, all 26 barangays of Sta. Cruz, Laguna
-- ---------------------------------------------------------------------
INSERT INTO naps (nap_code, name, address, latitude, longitude, total_ports, used_ports, available_ports, status) VALUES
('NAP-POB1-01', 'Poblacion I NAP 1', 'Purok 1, Brgy. Poblacion I, Sta. Cruz, Laguna', 14.2800000, 121.4130000, 24, 23, 1, 'active'),
('NAP-POB2-01', 'Poblacion II NAP 1', 'Purok 1, Brgy. Poblacion II, Sta. Cruz, Laguna', 14.2815000, 121.4145000, 16, 12, 4, 'active'),
('NAP-POB3-01', 'Poblacion III NAP 1', 'Purok 1, Brgy. Poblacion III, Sta. Cruz, Laguna', 14.2825000, 121.4160000, 8, 6, 2, 'maintenance'),
('NAP-POB4-01', 'Poblacion IV NAP 1', 'Purok 1, Brgy. Poblacion IV, Sta. Cruz, Laguna', 14.2795000, 121.4175000, 24, 10, 14, 'maintenance'),
('NAP-POB5-01', 'Poblacion V NAP 1', 'Purok 1, Brgy. Poblacion V, Sta. Cruz, Laguna', 14.2780000, 121.4155000, 8, 1, 7, 'active'),
('NAP-BGB-01', 'Bagumbayan NAP 1', 'Purok 1, Brgy. Bagumbayan, Sta. Cruz, Laguna', 14.2840000, 121.4120000, 16, 16, 0, 'full'),
('NAP-SSC-01', 'Santisima Cruz NAP 1', 'Purok 1, Brgy. Santisima Cruz, Sta. Cruz, Laguna', 14.2870000, 121.4100000, 16, 9, 7, 'maintenance'),
('NAP-SAC-01', 'Santo Angel Central NAP 1', 'Purok 1, Brgy. Santo Angel Central, Sta. Cruz, Laguna', 14.2890000, 121.4130000, 24, 24, 0, 'full'),
('NAP-SAN1-01', 'Santo Angel Norte NAP 1', 'Purok 1, Brgy. Santo Angel Norte, Sta. Cruz, Laguna', 14.2915000, 121.4145000, 24, 18, 6, 'active'),
('NAP-SAS-01', 'Santo Angel Sur NAP 1', 'Purok 1, Brgy. Santo Angel Sur, Sta. Cruz, Laguna', 14.2860000, 121.4165000, 16, 0, 16, 'inactive'),
('NAP-SPN-01', 'San Pablo Norte NAP 1', 'Purok 1, Brgy. San Pablo Norte, Sta. Cruz, Laguna', 14.2940000, 121.4110000, 24, 0, 24, 'inactive'),
('NAP-SPS-01', 'San Pablo Sur NAP 1', 'Purok 1, Brgy. San Pablo Sur, Sta. Cruz, Laguna', 14.2905000, 121.4085000, 8, 3, 5, 'active'),
('NAP-BUB-01', 'Bubukal NAP 1', 'Purok 1, Brgy. Bubukal, Sta. Cruz, Laguna', 14.2735000, 121.4055000, 16, 16, 0, 'full'),
('NAP-CAL-01', 'Calios NAP 1', 'Purok 1, Brgy. Calios, Sta. Cruz, Laguna', 14.2901000, 121.4211000, 16, 16, 0, 'full'),
('NAP-DUH-01', 'Duhat NAP 1', 'Purok 1, Brgy. Duhat, Sta. Cruz, Laguna', 14.2760000, 121.4225000, 16, 0, 16, 'inactive'),
('NAP-GAT-01', 'Gatid NAP 1', 'Purok 1, Brgy. Gatid, Sta. Cruz, Laguna', 14.2700000, 121.4190000, 8, 8, 0, 'active'),
('NAP-JAS-01', 'Jasaan NAP 1', 'Purok 1, Brgy. Jasaan, Sta. Cruz, Laguna', 14.2650000, 121.4290000, 16, 14, 2, 'active'),
('NAP-LAB-01', 'Labuin NAP 1', 'Purok 1, Brgy. Labuin, Sta. Cruz, Laguna', 14.2680000, 121.4160000, 24, 1, 23, 'active'),
('NAP-MAL-01', 'Malinao NAP 1', 'Purok 1, Brgy. Malinao, Sta. Cruz, Laguna', 14.2620000, 121.4230000, 24, 6, 18, 'active'),
('NAP-OOG-01', 'Oogong NAP 1', 'Purok 1, Brgy. Oogong, Sta. Cruz, Laguna', 14.2600000, 121.4320000, 16, 13, 3, 'maintenance'),
('NAP-PAG-01', 'Pagsawitan NAP 1', 'Purok 1, Brgy. Pagsawitan, Sta. Cruz, Laguna', 14.2745000, 121.4280000, 16, 16, 0, 'full'),
('NAP-PAL-01', 'Palasan NAP 1', 'Purok 1, Brgy. Palasan, Sta. Cruz, Laguna', 14.2560000, 121.4260000, 16, 12, 4, 'active'),
('NAP-PAT-01', 'Patimbao NAP 1', 'Purok 1, Brgy. Patimbao, Sta. Cruz, Laguna', 14.2690000, 121.4340000, 16, 16, 0, 'full'),
('NAP-SJO-01', 'San Jose NAP 1', 'Purok 1, Brgy. San Jose, Sta. Cruz, Laguna', 14.2530000, 121.4300000, 16, 12, 4, 'active'),
('NAP-SJN-01', 'San Juan NAP 1', 'Purok 1, Brgy. San Juan, Sta. Cruz, Laguna', 14.2585000, 121.4370000, 24, 17, 7, 'active'),
('NAP-ALP-01', 'Alipit NAP 1', 'Purok 1, Brgy. Alipit, Sta. Cruz, Laguna', 14.2480000, 121.4230000, 24, 4, 20, 'active');

-- ---------------------------------------------------------------------
-- subscribers -- 1-3 randomly generated subscribers per NAP ("random
-- connection" per barangay). SUB-0001 stays linked to the customer1
-- user account (users.id = 5) for portal-login continuity; every other
-- subscriber is unlinked (user_id NULL), same as the previous seed.
-- ---------------------------------------------------------------------
INSERT INTO subscribers (subscriber_code, full_name, address, latitude, longitude, contact_number, email, plan_type, nap_id, user_id, status, installed_at) VALUES
('SUB-0001', 'Ana Villanueva', '190 Purok 5, Brgy. Poblacion I, Sta. Cruz, Laguna', 14.2787023, 121.4115690, '09171111111', 'ana.villanueva@example.com', 'Home 100 Mbps', 1, 5, 'active', '2025-01-07'),
('SUB-0002', 'Marco De Leon', '184 Purok 6, Brgy. Poblacion I, Sta. Cruz, Laguna', 14.2803673, 121.4132205, '09923041955', 'marco.de.leon@example.com', 'Home 100 Mbps', 1, NULL, 'active', '2025-05-09'),
('SUB-0003', 'Roberto Panganiban', '12 Purok 6, Brgy. Poblacion II, Sta. Cruz, Laguna', 14.2809382, 121.4136523, '09663303705', 'roberto.panganiban@example.com', 'Home 25 Mbps', 2, NULL, 'active', '2025-04-03'),
('SUB-0004', 'Precious Del Rosario', '91 Purok 2, Brgy. Poblacion III, Sta. Cruz, Laguna', 14.2837028, 121.4147856, '09889595113', 'precious.del.rosario@example.com', 'Business 100 Mbps', 3, NULL, 'active', '2025-06-21'),
('SUB-0005', 'Pedro Cruz', '63 Purok 2, Brgy. Poblacion III, Sta. Cruz, Laguna', 14.2829859, 121.4161229, '09666348124', 'pedro.cruz@example.com', 'Home 100 Mbps', 3, NULL, 'active', '2025-06-23'),
('SUB-0006', 'Leonor Pascual', '118 Purok 2, Brgy. Poblacion IV, Sta. Cruz, Laguna', 14.2791243, 121.4189924, '09454412919', 'leonor.pascual@example.com', 'Home 50 Mbps', 4, NULL, 'active', '2025-05-18'),
('SUB-0007', 'Carmen Mendoza', '109 Purok 5, Brgy. Poblacion V, Sta. Cruz, Laguna', 14.2784588, 121.4165515, '09238212356', 'carmen.mendoza@example.com', 'Home 100 Mbps', 5, NULL, 'active', '2025-04-17'),
('SUB-0008', 'Fernando Castillo', '185 Purok 6, Brgy. Bagumbayan, Sta. Cruz, Laguna', 14.2827694, 121.4102117, '09452811832', 'fernando.castillo@example.com', 'Home 50 Mbps', 6, NULL, 'active', '2025-01-28'),
('SUB-0009', 'Renato Santos', '18 Purok 7, Brgy. Santisima Cruz, Sta. Cruz, Laguna', 14.2855084, 121.4099496, '09741988889', 'renato.santos@example.com', 'Home 50 Mbps', 7, NULL, 'active', '2025-04-18'),
('SUB-0010', 'Angelica Ocampo', '133 Purok 4, Brgy. Santo Angel Central, Sta. Cruz, Laguna', 14.2895396, 121.4127772, '09299927269', 'angelica.ocampo@example.com', 'Home 50 Mbps', 8, NULL, 'active', '2025-03-01'),
('SUB-0011', 'Susan Salazar', '19 Purok 6, Brgy. Santo Angel Central, Sta. Cruz, Laguna', 14.2880284, 121.4119928, '09847641645', 'susan.salazar@example.com', 'Home 25 Mbps', 8, NULL, 'active', '2025-01-28'),
('SUB-0012', 'Arnel Villanueva', '49 Purok 1, Brgy. Santo Angel Norte, Sta. Cruz, Laguna', 14.2925246, 121.4156070, '09274078666', 'arnel.villanueva@example.com', 'Home 100 Mbps', 9, NULL, 'active', '2025-04-15'),
('SUB-0013', 'Hernan Reyes', '26 Purok 1, Brgy. Santo Angel Norte, Sta. Cruz, Laguna', 14.2921241, 121.4162430, '09602311310', 'hernan.reyes@example.com', 'Business 100 Mbps', 9, NULL, 'active', '2025-01-08'),
('SUB-0014', 'Julius Aquino', '47 Purok 3, Brgy. Santo Angel Norte, Sta. Cruz, Laguna', 14.2916306, 121.4132047, '09666743109', 'julius.aquino@example.com', 'Home 50 Mbps', 9, NULL, 'active', '2025-01-15'),
('SUB-0015', 'Eduardo Dela Cruz', '117 Purok 3, Brgy. Santo Angel Sur, Sta. Cruz, Laguna', 14.2877471, 121.4156547, '09624200826', 'eduardo.dela.cruz@example.com', 'Home 100 Mbps', 10, NULL, 'active', '2025-03-07'),
('SUB-0016', 'Ramon Reyes', '48 Purok 1, Brgy. San Pablo Norte, Sta. Cruz, Laguna', 14.2956588, 121.4094884, '09808914080', 'ramon.reyes@example.com', 'Home 25 Mbps', 11, NULL, 'active', '2025-02-13'),
('SUB-0017', 'Carmen Tolentino', '11 Purok 5, Brgy. San Pablo Norte, Sta. Cruz, Laguna', 14.2942508, 121.4112841, '09258029013', 'carmen.tolentino@example.com', 'Home 100 Mbps', 11, NULL, 'active', '2025-05-17'),
('SUB-0018', 'Danilo Espiritu', '81 Purok 2, Brgy. San Pablo Norte, Sta. Cruz, Laguna', 14.2931388, 121.4116110, '09455201412', 'danilo.espiritu@example.com', 'Home 100 Mbps', 11, NULL, 'active', '2025-06-10'),
('SUB-0019', 'Ricardo Mendoza', '63 Purok 3, Brgy. San Pablo Sur, Sta. Cruz, Laguna', 14.2920597, 121.4098711, '09476002884', 'ricardo.mendoza@example.com', 'Home 50 Mbps', 12, NULL, 'active', '2025-05-23'),
('SUB-0020', 'Grace Cruz', '136 Purok 1, Brgy. San Pablo Sur, Sta. Cruz, Laguna', 14.2922419, 121.4096056, '09887112652', 'grace.cruz@example.com', 'Business 100 Mbps', 12, NULL, 'active', '2025-01-05'),
('SUB-0021', 'Ricardo Bautista', '40 Purok 3, Brgy. San Pablo Sur, Sta. Cruz, Laguna', 14.2919030, 121.4093727, '09472533494', 'ricardo.bautista@example.com', 'Home 50 Mbps', 12, NULL, 'active', '2025-02-22'),
('SUB-0022', 'Fe Rivera', '3 Purok 1, Brgy. Bubukal, Sta. Cruz, Laguna', 14.2736860, 121.4052397, '09250792472', 'fe.rivera@example.com', 'Home 50 Mbps', 13, NULL, 'active', '2025-07-12'),
('SUB-0023', 'Fe Mendoza', '42 Purok 7, Brgy. Calios, Sta. Cruz, Laguna', 14.2916327, 121.4201523, '09360108532', 'fe.mendoza@example.com', 'Home 100 Mbps', 14, NULL, 'inactive', '2025-06-11'),
('SUB-0024', 'Vicente Marasigan', '64 Purok 3, Brgy. Calios, Sta. Cruz, Laguna', 14.2907117, 121.4219462, '09340937380', 'vicente.marasigan@example.com', 'Home 25 Mbps', 14, NULL, 'active', '2025-01-28'),
('SUB-0025', 'Julius Ilagan', '59 Purok 2, Brgy. Calios, Sta. Cruz, Laguna', 14.2916064, 121.4205588, '09195409494', 'julius.ilagan@example.com', 'Home 50 Mbps', 14, NULL, 'active', '2025-03-28'),
('SUB-0026', 'Ricardo Ramos', '10 Purok 1, Brgy. Duhat, Sta. Cruz, Laguna', 14.2762901, 121.4242408, '09810563507', 'ricardo.ramos@example.com', 'Home 100 Mbps', 15, NULL, 'active', '2025-07-11'),
('SUB-0027', 'Hernan Domingo', '111 Purok 1, Brgy. Gatid, Sta. Cruz, Laguna', 14.2708533, 121.4179093, '09883219781', 'hernan.domingo@example.com', 'Business 100 Mbps', 16, NULL, 'active', '2025-06-28'),
('SUB-0028', 'Carmen Domingo', '171 Purok 4, Brgy. Gatid, Sta. Cruz, Laguna', 14.2714402, 121.4190256, '09520236225', 'carmen.domingo@example.com', 'Home 100 Mbps', 16, NULL, 'active', '2025-05-05'),
('SUB-0029', 'Julius Castillo', '192 Purok 2, Brgy. Gatid, Sta. Cruz, Laguna', 14.2705937, 121.4185649, '09830904107', 'julius.castillo@example.com', 'Business 100 Mbps', 16, NULL, 'active', '2025-07-01'),
('SUB-0030', 'Liza De Leon', '189 Purok 2, Brgy. Jasaan, Sta. Cruz, Laguna', 14.2649035, 121.4304443, '09877435606', 'liza.de.leon@example.com', 'Home 25 Mbps', 17, NULL, 'active', '2025-06-21'),
('SUB-0031', 'Jocelyn Torres', '61 Purok 6, Brgy. Jasaan, Sta. Cruz, Laguna', 14.2635362, 121.4306272, '09503310361', 'jocelyn.torres@example.com', 'Home 50 Mbps', 17, NULL, 'active', '2025-02-01'),
('SUB-0032', 'Jose Villanueva', '197 Purok 1, Brgy. Jasaan, Sta. Cruz, Laguna', 14.2667422, 121.4294006, '09658999385', 'jose.villanueva@example.com', 'Home 100 Mbps', 17, NULL, 'active', '2025-05-07'),
('SUB-0033', 'Paolo Espiritu', '119 Purok 6, Brgy. Labuin, Sta. Cruz, Laguna', 14.2692540, 121.4158433, '09740298515', 'paolo.espiritu@example.com', 'Business 100 Mbps', 18, NULL, 'active', '2025-04-20'),
('SUB-0034', 'Hernan Tolentino', '141 Purok 4, Brgy. Labuin, Sta. Cruz, Laguna', 14.2680172, 121.4171900, '09340894498', 'hernan.tolentino@example.com', 'Home 100 Mbps', 18, NULL, 'active', '2025-07-08'),
('SUB-0035', 'Cesar Fernandez', '161 Purok 2, Brgy. Labuin, Sta. Cruz, Laguna', 14.2689569, 121.4160767, '09464846763', 'cesar.fernandez@example.com', 'Home 100 Mbps', 18, NULL, 'inactive', '2025-03-08'),
('SUB-0036', 'Vicente Castillo', '16 Purok 2, Brgy. Malinao, Sta. Cruz, Laguna', 14.2613912, 121.4228773, '09621125671', 'vicente.castillo@example.com', 'Home 100 Mbps', 19, NULL, 'active', '2025-05-23'),
('SUB-0037', 'Fe Domingo', '57 Purok 4, Brgy. Oogong, Sta. Cruz, Laguna', 14.2601661, 121.4323717, '09405602191', 'fe.domingo@example.com', 'Business 100 Mbps', 20, NULL, 'active', '2025-01-13'),
('SUB-0038', 'Josefina Ocampo', '43 Purok 7, Brgy. Oogong, Sta. Cruz, Laguna', 14.2606449, 121.4316555, '09671856351', 'josefina.ocampo@example.com', 'Home 50 Mbps', 20, NULL, 'active', '2025-05-01'),
('SUB-0039', 'Angelica Navarro', '165 Purok 4, Brgy. Oogong, Sta. Cruz, Laguna', 14.2602318, 121.4302976, '09315706210', 'angelica.navarro@example.com', 'Home 100 Mbps', 20, NULL, 'active', '2025-03-13'),
('SUB-0040', 'Rosa Pascual', '90 Purok 2, Brgy. Pagsawitan, Sta. Cruz, Laguna', 14.2727698, 121.4281419, '09868086909', 'rosa.pascual@example.com', 'Home 25 Mbps', 21, NULL, 'active', '2025-06-02'),
('SUB-0041', 'Isagani Dela Cruz', '6 Purok 5, Brgy. Pagsawitan, Sta. Cruz, Laguna', 14.2761186, 121.4269177, '09333619298', 'isagani.dela.cruz@example.com', 'Home 50 Mbps', 21, NULL, 'active', '2025-06-04'),
('SUB-0042', 'Imelda Aquino', '161 Purok 2, Brgy. Palasan, Sta. Cruz, Laguna', 14.2544736, 121.4266862, '09279415691', 'imelda.aquino@example.com', 'Business 100 Mbps', 22, NULL, 'active', '2025-05-26'),
('SUB-0043', 'Carmen Marasigan', '89 Purok 5, Brgy. Palasan, Sta. Cruz, Laguna', 14.2577418, 121.4270175, '09629967386', 'carmen.marasigan@example.com', 'Business 100 Mbps', 22, NULL, 'inactive', '2025-06-11'),
('SUB-0044', 'Hernan De Leon', '138 Purok 7, Brgy. Patimbao, Sta. Cruz, Laguna', 14.2706757, 121.4331723, '09689151495', 'hernan.de.leon@example.com', 'Home 100 Mbps', 23, NULL, 'active', '2025-06-19'),
('SUB-0045', 'Maria Pascual', '55 Purok 3, Brgy. San Jose, Sta. Cruz, Laguna', 14.2542634, 121.4288546, '09447403790', 'maria.pascual@example.com', 'Business 100 Mbps', 24, NULL, 'active', '2025-05-23'),
('SUB-0046', 'Elena Salazar', '22 Purok 2, Brgy. San Jose, Sta. Cruz, Laguna', 14.2512365, 121.4316130, '09943174285', 'elena.salazar@example.com', 'Home 100 Mbps', 24, NULL, 'active', '2025-07-08'),
('SUB-0047', 'Roberto Castillo', '91 Purok 6, Brgy. San Juan, Sta. Cruz, Laguna', 14.2602879, 121.4371814, '09657205269', 'roberto.castillo@example.com', 'Business 100 Mbps', 25, NULL, 'active', '2025-02-04'),
('SUB-0048', 'Hernan Aquino', '196 Purok 6, Brgy. San Juan, Sta. Cruz, Laguna', 14.2578360, 121.4378744, '09368803134', 'hernan.aquino@example.com', 'Home 50 Mbps', 25, NULL, 'active', '2025-04-09'),
('SUB-0049', 'Hernan Navarro', '73 Purok 1, Brgy. San Juan, Sta. Cruz, Laguna', 14.2602158, 121.4370887, '09378432166', 'hernan.navarro@example.com', 'Business 100 Mbps', 25, NULL, 'active', '2025-02-10'),
('SUB-0050', 'Isagani Pascual', '73 Purok 4, Brgy. Alipit, Sta. Cruz, Laguna', 14.2465693, 121.4212442, '09684015466', 'isagani.pascual@example.com', 'Home 100 Mbps', 26, NULL, 'active', '2025-01-09'),
('SUB-0051', 'Arnel Bautista', '19 Purok 5, Brgy. Alipit, Sta. Cruz, Laguna', 14.2491596, 121.4226425, '09845862179', 'arnel.bautista@example.com', 'Home 25 Mbps', 26, NULL, 'active', '2025-07-19'),
('SUB-0052', 'Grace Santos', '196 Purok 4, Brgy. Alipit, Sta. Cruz, Laguna', 14.2497781, 121.4216264, '09821028618', 'grace.santos@example.com', 'Home 50 Mbps', 26, NULL, 'active', '2025-04-15');

-- ---------------------------------------------------------------------
-- technicians (linked to the technician user accounts above)
-- ---------------------------------------------------------------------
INSERT INTO technicians (user_id, full_name, contact_number, personnel_type, current_latitude, current_longitude, status, resolved_issues_count) VALUES
(2, 'Marco Reyes',    '09170000002', 'field_assistant', 14.2800000, 121.4140000, 'available', 14),
(3, 'Liza Fernandez',  '09170000003', 'field_assistant', 14.2750000, 121.4060000, 'busy',      9);

-- ---------------------------------------------------------------------
-- technical_issues -- 0-2 randomly generated reported issues per NAP,
-- each pinned at its subscriber's EXACT coordinates (see PIN-ERROR note
-- in app/routes/issues.py -- an issue's location must exactly match the
-- subscriber it's reported against).
-- ---------------------------------------------------------------------
INSERT INTO technical_issues (issue_code, issue_type, description, priority, status, address, latitude, longitude, subscriber_id, nap_id) VALUES
('ISS-0001', 'Other', 'Subscriber says the box near their house looks physically damaged.', 'medium', 'pending', '190 Purok 5, Brgy. Poblacion I, Sta. Cruz, Laguna', 14.2787023, 121.4115690, 1, 1),
('ISS-0002', 'Other', 'Reported burnt/damaged drop cable near the NAP.', 'medium', 'in_progress', '12 Purok 6, Brgy. Poblacion II, Sta. Cruz, Laguna', 14.2809382, 121.4136523, 3, 2),
('ISS-0003', 'Other', 'ONT keeps losing signal (LOS light red).', 'high', 'closed', '12 Purok 6, Brgy. Poblacion II, Sta. Cruz, Laguna', 14.2809382, 121.4136523, 3, 2),
('ISS-0004', 'Other', 'Reported burnt/damaged drop cable near the NAP.', 'high', 'in_progress', '91 Purok 2, Brgy. Poblacion III, Sta. Cruz, Laguna', 14.2837028, 121.4147856, 4, 3),
('ISS-0005', 'No Internet', 'Reported burnt/damaged drop cable near the NAP.', 'medium', 'pending', '91 Purok 2, Brgy. Poblacion III, Sta. Cruz, Laguna', 14.2837028, 121.4147856, 4, 3),
('ISS-0006', 'Connection Problem', 'Subscriber says the box near their house looks physically damaged.', 'medium', 'closed', '118 Purok 2, Brgy. Poblacion IV, Sta. Cruz, Laguna', 14.2791243, 121.4189924, 6, 4),
('ISS-0007', 'Other', 'Intermittent slow speeds during peak hours.', 'medium', 'assigned', '109 Purok 5, Brgy. Poblacion V, Sta. Cruz, Laguna', 14.2784588, 121.4165515, 7, 5),
('ISS-0008', 'Other', 'ONT keeps losing signal (LOS light red).', 'low', 'in_progress', '185 Purok 6, Brgy. Bagumbayan, Sta. Cruz, Laguna', 14.2827694, 121.4102117, 8, 6),
('ISS-0009', 'Connection Problem', 'Reported burnt/damaged drop cable near the NAP.', 'medium', 'pending', '185 Purok 6, Brgy. Bagumbayan, Sta. Cruz, Laguna', 14.2827694, 121.4102117, 8, 6),
('ISS-0010', 'Connection Problem', 'Subscriber says the box near their house looks physically damaged.', 'critical', 'closed', '18 Purok 7, Brgy. Santisima Cruz, Sta. Cruz, Laguna', 14.2855084, 121.4099496, 9, 7),
('ISS-0011', 'Connection Problem', 'ONT keeps losing signal (LOS light red).', 'low', 'assigned', '133 Purok 4, Brgy. Santo Angel Central, Sta. Cruz, Laguna', 14.2895396, 121.4127772, 10, 8),
('ISS-0012', 'No Internet', 'Subscriber reports no internet since this morning.', 'critical', 'closed', '49 Purok 1, Brgy. Santo Angel Norte, Sta. Cruz, Laguna', 14.2925246, 121.4156070, 12, 9),
('ISS-0013', 'Slow Internet', 'Subscriber says the box near their house looks physically damaged.', 'medium', 'pending', '49 Purok 1, Brgy. Santo Angel Norte, Sta. Cruz, Laguna', 14.2925246, 121.4156070, 12, 9),
('ISS-0014', 'Other', 'Reported burnt/damaged drop cable near the NAP.', 'low', 'assigned', '117 Purok 3, Brgy. Santo Angel Sur, Sta. Cruz, Laguna', 14.2877471, 121.4156547, 15, 10),
('ISS-0015', 'No Internet', 'Subscriber reports no internet since this morning.', 'medium', 'closed', '11 Purok 5, Brgy. San Pablo Norte, Sta. Cruz, Laguna', 14.2942508, 121.4112841, 17, 11),
('ISS-0016', 'Connection Problem', 'Speed test consistently below the subscribed plan.', 'low', 'closed', '136 Purok 1, Brgy. San Pablo Sur, Sta. Cruz, Laguna', 14.2922419, 121.4096056, 20, 12),
('ISS-0017', 'No Internet', 'Subscriber says the box near their house looks physically damaged.', 'high', 'pending', '63 Purok 3, Brgy. San Pablo Sur, Sta. Cruz, Laguna', 14.2920597, 121.4098711, 19, 12),
('ISS-0018', 'NAP Problem', 'Connection drops every few hours.', 'low', 'pending', '3 Purok 1, Brgy. Bubukal, Sta. Cruz, Laguna', 14.2736860, 121.4052397, 22, 13),
('ISS-0019', 'Fiber/Cable Problem', 'ONT keeps losing signal (LOS light red).', 'medium', 'in_progress', '3 Purok 1, Brgy. Bubukal, Sta. Cruz, Laguna', 14.2736860, 121.4052397, 22, 13),
('ISS-0020', 'Fiber/Cable Problem', 'Subscriber says the box near their house looks physically damaged.', 'medium', 'resolved', '64 Purok 3, Brgy. Calios, Sta. Cruz, Laguna', 14.2907117, 121.4219462, 24, 14),
('ISS-0021', 'NAP Problem', 'ONT keeps losing signal (LOS light red).', 'low', 'in_progress', '10 Purok 1, Brgy. Duhat, Sta. Cruz, Laguna', 14.2762901, 121.4242408, 26, 15),
('ISS-0022', 'Slow Internet', 'Subscriber says the box near their house looks physically damaged.', 'high', 'in_progress', '171 Purok 4, Brgy. Gatid, Sta. Cruz, Laguna', 14.2714402, 121.4190256, 28, 16),
('ISS-0023', 'NAP Problem', 'Speed test consistently below the subscribed plan.', 'medium', 'pending', '197 Purok 1, Brgy. Jasaan, Sta. Cruz, Laguna', 14.2667422, 121.4294006, 32, 17),
('ISS-0024', 'No Internet', 'Intermittent slow speeds during peak hours.', 'high', 'pending', '197 Purok 1, Brgy. Jasaan, Sta. Cruz, Laguna', 14.2667422, 121.4294006, 32, 17),
('ISS-0025', 'Fiber/Cable Problem', 'Intermittent slow speeds during peak hours.', 'low', 'pending', '141 Purok 4, Brgy. Labuin, Sta. Cruz, Laguna', 14.2680172, 121.4171900, 34, 18),
('ISS-0026', 'NAP Problem', 'Subscriber reports no internet since this morning.', 'critical', 'pending', '16 Purok 2, Brgy. Malinao, Sta. Cruz, Laguna', 14.2613912, 121.4228773, 36, 19),
('ISS-0027', 'NAP Problem', 'Reported burnt/damaged drop cable near the NAP.', 'medium', 'resolved', '57 Purok 4, Brgy. Oogong, Sta. Cruz, Laguna', 14.2601661, 121.4323717, 37, 20),
('ISS-0028', 'NAP Problem', 'Router reboots randomly, needs on-site check.', 'high', 'pending', '90 Purok 2, Brgy. Pagsawitan, Sta. Cruz, Laguna', 14.2727698, 121.4281419, 40, 21),
('ISS-0029', 'Slow Internet', 'Router reboots randomly, needs on-site check.', 'low', 'pending', '90 Purok 2, Brgy. Pagsawitan, Sta. Cruz, Laguna', 14.2727698, 121.4281419, 40, 21),
('ISS-0030', 'NAP Problem', 'Intermittent slow speeds during peak hours.', 'medium', 'pending', '89 Purok 5, Brgy. Palasan, Sta. Cruz, Laguna', 14.2577418, 121.4270175, 43, 22),
('ISS-0031', 'Slow Internet', 'Intermittent slow speeds during peak hours.', 'low', 'assigned', '138 Purok 7, Brgy. Patimbao, Sta. Cruz, Laguna', 14.2706757, 121.4331723, 44, 23),
('ISS-0032', 'Other', 'Speed test consistently below the subscribed plan.', 'medium', 'pending', '22 Purok 2, Brgy. San Jose, Sta. Cruz, Laguna', 14.2512365, 121.4316130, 46, 24),
('ISS-0033', 'Slow Internet', 'Subscriber says the box near their house looks physically damaged.', 'medium', 'pending', '22 Purok 2, Brgy. San Jose, Sta. Cruz, Laguna', 14.2512365, 121.4316130, 46, 24),
('ISS-0034', 'Connection Problem', 'Connection drops every few hours.', 'low', 'closed', '73 Purok 1, Brgy. San Juan, Sta. Cruz, Laguna', 14.2602158, 121.4370887, 49, 25),
('ISS-0035', 'Connection Problem', 'Subscriber says the box near their house looks physically damaged.', 'medium', 'in_progress', '19 Purok 5, Brgy. Alipit, Sta. Cruz, Laguna', 14.2491596, 121.4226425, 51, 26);

-- ---------------------------------------------------------------------
-- service_requests
-- ---------------------------------------------------------------------
INSERT INTO service_requests (request_type, subscriber_id, requested_nap_id, status, notes) VALUES
('new_installation', NULL, 1, 'pending',   'Walk-in applicant near Poblacion I NAP 1, awaiting site survey.'),
('upgrade',          40, 21, 'approved',  'Upgrading plan tier per subscriber request.'),
('relocation',       48, NULL, 'pending','Subscriber moving to a new address within the same barangay.'),
('new_installation', NULL, 14, 'scheduled', 'Site survey scheduled near Calios NAP 1.'),
('disconnection',    7, NULL, 'completed', 'Subscriber requested account closure.');

-- ---------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------
INSERT INTO payments (subscriber_id, collector_id, amount, payment_method, payment_date, reference_number, status) VALUES
(41, 4, 1599.00, 'cash', '2025-02-27', 'RCPT-0001', 'confirmed'),
(14, 4, 1299.00, 'gcash', '2025-02-10', 'RCPT-0002', 'confirmed'),
(17, 4, 2499.00, 'bank_transfer', '2025-04-25', 'RCPT-0003', 'pending'),
(43, 4, 1999.00, 'cash', '2025-01-17', 'RCPT-0004', 'overdue'),
(6, 4, 1999.00, 'gcash', '2025-06-19', 'RCPT-0005', 'confirmed'),
(11, 4, 2499.00, 'cash', '2025-01-17', 'RCPT-0006', 'confirmed');

-- ---------------------------------------------------------------------
-- assignments -- one per currently-open (assigned/in_progress) issue,
-- alternating between the two seeded technicians.
-- ---------------------------------------------------------------------
INSERT INTO assignments (technical_issue_id, technician_id, status, dispatch_score, completed_at) VALUES
(2, 1, 'in_progress', 96.79, NULL),
(4, 2, 'in_progress', 92.85, NULL),
(7, 1, 'assigned', 88.13, NULL),
(8, 2, 'in_progress', 89.17, NULL),
(11, 1, 'assigned', 97.08, NULL),
(14, 2, 'assigned', 82.33, NULL),
(19, 1, 'in_progress', 85.79, NULL),
(21, 2, 'in_progress', 88.78, NULL),
(22, 1, 'in_progress', 96.34, NULL),
(31, 2, 'assigned', 93.97, NULL),
(35, 1, 'in_progress', 72.07, NULL);

-- ---------------------------------------------------------------------
-- app_settings (Phase 15) — schema.sql already inserts the default
-- singleton row via INSERT IGNORE, so there's nothing further to seed
-- here; this note just documents why no INSERT appears in this file.
-- ---------------------------------------------------------------------
